[build.environment]
  TZ = "America/New_York"
  NODE_ENV = "Production"

[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  # Optional (but highly recommended). Defaults to [".cache"].
  paths = [".cache"]
