# https://javascript.works-hub.com/learn/how-to-create-a-ci-slash-cd-pipeline-using-netlify-and-github-actions-90aeb
name: "Build Pipeline"
on: 
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - name: Install dependencies
      run: npm install     
    - name: Build file
      run: npm run pbuild
    - name: Commit report
      run: |
        git config --global user.name 'John M. Wargo'
        git config --global user.email 'johnwargo@users.noreply.github.com'
        git commit -am "Automated Build (GitHub Actions)"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}      
      
    # // deploy the application to netlify
    # - name: Deploy production to Netlify
    #   uses: South-Paw/action-netlify-deploy@v1.2.0
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #     netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
    #     build-dir: './build'
    #     comment-on-commit: true